### PR TITLE
Customize calendar labels

### PR DESCRIPTION
**Pull request by acrollet**
@istos we need a way to be able to have custom labels on blocking events - here's one possibility, less obtrusive, but I don't know if we just need to let events have names? Even if they do we might want a separate, trimmed field for display purposes.

### CODE REVIEW

**Comment by istos** [comment]
I think we should parametrize this and allow the user to pick from which field to get the Event label for a given event - using the same pattern we use to allow users to pick the field from which the default value comes from.

**Comment by qcutter** [comment]
I agree. Or the Event label could leverage tokens with a default text field for something common. That way they could use combination of titles if they like (i.e. [content:title] - [content:owner]). Either way, I can't wait to plug this in and use it. Any roadmap or dates?

**Comment by istos** [comment]
Tokens sounds like an even better idea :-) Mind sharing some more about your use case for BAT? Might help inform how we add this. The feature is relatively high up in our agenda - hopefully this week.

**Comment by qcutter** [comment]
Sure, We are prototyping a concept where our members get to admin the booking of 3 types of booking resources with add ons that they define. This involves us allowing members to allow booking 3 different types of items for referenced entity (and possibly more in the future). We would be displaying all of the items on the main entity's calendar and being able to apply labeling that leverages tokens would open up a great number of possibilities now and going forward. We could have invite based bookings labeled (John's invite to the party) or (click here to book, and  have that linked to the booking process). I have been playing with early dev versions, but I have also run into issues using organic groups, inline entity form, and field collection module to allow the encapsulation of the booking process. So, will keep you updated on how this goes.

**Comment by qcutter** [comment]
Im sorry if that wasn't fairly clear. We are hoping to use BAT as a combination multi tier booking service and directory of booking of events created from completing a booking. With that, we will have events that would greatly benefit from contextual titles that we can setup the naming structure for and when people create or accept a booking it can also be contextually labeled according to taxonomy, status, availability, etc. Leveraging Token would open a great number of possibilities :)

**Comment by istos** [comment]
Nice - thanks for sharing. Helps a lot to think about different use cases!

**Comment by acrollet** [comment]
@qcutter: we now support selecting a field to pull event labels from when editing an event type. This doesn't on its own support tokenized labels, but you can get there with e.g. https://www.drupal.org/project/field_default_token - or simply hiding your field from the end user and setting its value programatically when events are created.

**Pull request merged**
